### PR TITLE
Bugfix/wrong winner displayed

### PR DESCRIPTION
**Pull request by rjs68**
Issue #43 where wrong winner was being displayed
-In game the cards from a round are collected up before being distributed to the winner
-Previously the game was removing players between these 2 steps
-It was incorrectly removing players who had won the round but had not yet been handed their winning cards
-The remove player steps have been moved to after the point where cards have been redistributed to the winner - so it now removes the right players
-Had to create new setRemovedPlayers() method in RoundOutcome as this could no longer be passed through the constructor

### CODE REVIEW

**Review by hughwin — APPROVED** [review]
Tested it! Works perfectly!

**Comment by BelfDev** [comment]
Can we hold this for a second? The new logic in CLI addresses this issue.

**Comment by nathanieldschneider** [comment]
looks fucking garbage you suck

**Comment by rjs68** [comment]
Problem resolved in Pedro's refactor - no longer required here

**Pull request closed without merging**
